arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: true
output-dir: lib/generated
preferred-supported-locales: ["en"]
use-deferred-loading: true 