name: halalapp
description: "A Halal Food Checker Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.9
  flutter_markdown: ^0.6.20
  
  # Image Upload & Processing
  cloudinary_url_gen: ^1.0.0
  http: ^1.1.2
  path: ^1.8.3
  
  # Location and Prayer Times
  geolocator: ^10.1.0
  adhan: ^2.0.0
  intl: ^0.19.0
  
  # Barcode Scanner
  mobile_scanner: ^3.5.6
  
  # Image Picker & Processing
  image_picker: ^1.0.5
  google_generative_ai: ^0.2.0
  
  # Utils
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/splash_logo.png
  branding: assets/logo/branding.png
  color_dark: "#121212"
  image_dark: assets/logo/splash_logo_dark.png
  branding_dark: assets/logo/branding_dark.png

  android_12:
    image: assets/logo/splash_logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/logo/splash_logo_dark.png
    icon_background_color_dark: "#121212"

  web: false 